aws_access_key = "YOUR_ACCESS_KEY_HERE"
aws_secret_key = "YOUR_SECRET_KEY_HERE"
aws_region = "us-east-1"
instance_type = "t2.micro"
key_pair_name = "my-ssh-key"
jenkins_ami_id = "ami-0abcdef1234567890"
sonarqube_ami_id = "ami-0abcdef1234567890"
